### ISSUE TITLE
alt Worker load event is broken

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-js-module#105]
### Description of the problem

The "load" event is called before the worker is actually loaded/ready. When you try to emit something to the worker inside the load event, it won't send it.

When waiting for a few seconds with eg a timeout, it works fine.

### Reproduction steps

Create a worker, emit in load event.

### Expected behaviour

The worker to be ready when it sends load event.

### Operating system

Windows

### Version

release 8.8

### Scope

shared, client

**Comment by LeonMrBonnie** [comment]
Try reproducing this on dev
