### ISSUE TITLE
Update NodeJS version to newest LTS

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-js-module#11]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
The NodeJS version of the module should be updated to the current LTS. 
Current module version is v12.4.0, newest LTS is v12.18.4

The module could even be updated to NodeJS v14+, but sticking with LTS will probably be safer.

**Describe alternatives you've considered**
Crying

**Additional context**
-

**Comment by Pupskuchen** [comment]
v14 is LTS by now: https://nodejs.org/en/about/releases/

**Comment by Pupskuchen** [comment]
Which steps would be necessary to update the included NodeJS version?

**Comment by vadzz-dev** [comment]
Done in 708608f642d435365ae4ad00c8c7d7879260c655
