### ISSUE TITLE
`style` on rmlElement doesn't work

### ISSUE THREAD

**Issue by fauconjona** [altmp/altv-js-module#110]
### Description of the problem

If you define a style property on a RmlElement by using `.style['property']`, it affects the whole document.

### Reproduction steps

On any rmlElement:

```ts
function setColor(id: string, color: string) {
  let rmlElement = this.textDocument.getElementByID(id);
  
  if (rmlElement != null) {
	  rmlElement.style['color'] = color;
  }
}
```

### Expected behaviour

Ability to access and set a css property by using `.style`

### Additional context

Using `setProperty` works

### Operating system

Manjaro 21.2.1

### Version

9.0-rc2

### Scope

client

**Comment by LeonMrBonnie** [comment]
Is this still an issue?

**Comment by LeonMrBonnie** [comment]
Closing because I think its fixed and there was no response from the author
