### ISSUE TITLE
Client crashes with syntax error in top-level code

### ISSUE THREAD

**Issue by tobiasr97** [altmp/altv-js-module#111]
### Description of the problem

The client crashes if you write code like the one below.

### Reproduction steps

alt.onServer('text', ...arr => { });

### Expected behaviour

Im not sure if it is syntactically correct to write it like this, but at least the client should not crash.

### Additional context

alt.onServer('text', (...arr) => { });
Is totally fine.

### Operating system

Windows 10

### Version

9.0-rc2

### Scope

client

**Comment by tobiasr97** [comment]
`[15:11:17][Error] [V8] Exception at reallife:client/src/menus/supermarketMenu.js:7
[15:11:17][Error]   alt.on('text', ...arr => {
[15:11:17][Error] Failed to load resource reallife`
now this happens and the client does not crash at least, but the Server after some time

`Exitcode: 3221225477`

**Comment by tastydev** [comment]
This isn't valid Js syntax because it tries to iterate and destruct a not defined iterable on listener registration you need to use the callback syntax there

**Comment by xxshady** [comment]
Not only syntax errors crashes client
```js
[01:39:23][Error] [V8] Exception at main:client/main.js:194
[01:39:23][Error]         throw new Error(`${this.name} pool already defined`);
[01:39:23][Error] Failed to load resource main
[01:39:23] MINIDUMP: Temporary dump saved
[01:39:23] MINIDUMP: MiniDump created
```

**Comment by xxshady** [comment]
Also `Error.message` is not displayed, as you can see in the message above.
But in normal exceptions (e.g. in `alt.nextTick`) it is displayed:

![image](https://user-images.githubusercontent.com/54737754/152661850-5e3d1723-fd64-44a8-8942-06013d40b41c.png)

**Comment by LeonMrBonnie** [comment]
This was fixed some time already
