### ISSUE TITLE
Terminal frozen when stopping the server process

### ISSUE THREAD

**Issue by YannBcf** [altmp/altv-js-module#122]
### Description of the problem

Since the nodeJS 17 update (tested and doesn't happen on release) when you stop the server via CTRL + C the terminal is frozen and you have to kill the terminal.

### Reproduction steps

start an alt:V server in a terminal and stop the server process with CTRL + C

### Expected behaviour

*

### Operating system

Windows 10

### Version

dev/10.0-dev7

### Scope

server

**Comment by LeonMrBonnie** [comment]
https://github.com/altmp/altv-js-module/blob/b5a6d314b3a0d8e940e5ee147a4cec3520d1ce1c/server/src/CNodeResourceImpl.cpp#L94

**Comment by YannBcf** [comment]
Doesn't happen anymore, I think it was just a random issue
