### ISSUE TITLE
Link benchmark timers to resource

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#135]
### Description of the problem

Currently timers (`alt.time()`) are just static, which cause problems when using resource restart

### Desired solution for the problem

Timers should be linked to the creator resource and cleared on resource stop

### Version

dev/10.0-dev10

### Scope

shared

**Comment by LeonMrBonnie** [comment]
Which timers do you mean?

**Comment by xxshady** [comment]
benchmark timers
