### ISSUE TITLE
Error: Invalid connection info

### ISSUE THREAD

**Issue by h2e8c6g4x2** [altmp/altv-js-module#143]
### Description of the problem

I downloaded new server files (Development) and now while connection I receive this 
`[16:33:43][Error] Error: Invalid connection info `
I updated client as well.

### Reproduction steps

1. Start server in dev mode
2. Start client in dev mode (debug: true)
3. Connect to the server

### Expected behaviour

Successful connection as it used to be, receiving connection info

### Additional context

---- > server.cfg
name: 'alt:V Server'
host: 0.0.0.0
port: 7788
players: 10
#password: ultra-password
announce: false
debug: true
gamemode: Freeroam
website: example.com
language: en
description: 'alt:V Sample Server'
modules: ['js-module', 'csharp-module'] 
resources: ['chat', 'BetterNoClip', 'my_gamemode']
deps: []

---- > alt.cfg

branch: 'dev'
crashReporterEnabled: 'true'
debug: 'true'
earlyAuthTestURL: ''
gtapath: 'C:\\GAMES\\Grand Theft Auto V'
lang: 'en'
lastip: '127.0.0.1:7788'
name: 'admin'
netgraph: 'true'
promotedOnTop: 'false'
streamerMode: 'false'
useExternalConsole: 'false'
voiceActivationEnabled: 'false'
voiceActivationKey: '78'
voiceAutoInputVolume: 'true'
voiceEnabled: 'true'
voiceInputSensitivity: '20'
voiceInputVolume: '100'
voiceNoiseSuppression: 'true'
voiceVolume: '100'

### Operating system

Windows 10

### Version

altmp/altv-issues#10.0-DEV16

**Comment by LeonMrBonnie** [comment]
Are you using the connection queue or beforePlayerConnect event? And if yes, show the code how you use it

**Comment by h2e8c6g4x2** [comment]
> Are you using the connection queue or beforePlayerConnect event? And if yes, show the code how you use it

Sorry for a mistake. Ofc I use alt.on('beforePlayerConnect', player_connecting);

**Comment by LeonMrBonnie** [comment]
Show that function

**Comment by h2e8c6g4x2** [comment]
Please close the topic.
The issue was how I used it in timeout with 0 delay but it was too late to receive data.
