### ISSUE TITLE
Emit function sends invalid baseobjects as null values

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#152]
### Description of the problem

If you try emit invalid baseobject, it will be sent as null value and exception will be thrown for sender:
`Error: Unable to convert base object to MValue because it was destroyed and is now invalid`

### Reproduction steps

serverside code
```js
alt.on('test', (entity) => alt.log('received entity:', entity?.constructor.name, entity?.valid));

const veh = new alt.Vehicle('sultan', 0, 0, 0, 0, 0, 0);
veh.destroy();
alt.emit('test', veh);

```

### Expected behaviour

Event should not be sent?

### Operating system

Windows 11

### Version

release/10.1

### Scope

shared

**Comment by LeonMrBonnie** [comment]
And where is the bug here? That is the intended behaviour

**Comment by xxshady** [comment]
Then it should be documented and the typings fixed, i think

**Comment by LeonMrBonnie** [comment]
You can add that to the typings if you want.
