### ISSUE TITLE
Raw emiting invalid baseobject leads to a crash

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#153]
### Description of the problem

/

### Reproduction steps

```js
const veh = new alt.Vehicle("sultan2", 0, 0, 0, 0, 0, 0);

alt.emitRaw("test", veh) // ok
alt.log('sent');

alt.nextTick(() => {
  veh.destroy();
  alt.emitRaw("test", veh); // crash
})
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

dev/11.0/dev1

### Scope

shared

**Comment by tastydev** [comment]
does it also happen with `alt.emit`? it should happen there too i can fix it later

**Comment by xxshady** [comment]
raw emit only

**Comment by xxshady** [comment]
normal emit: #152

**Comment by xxshady** [comment]
Fixed in https://github.com/altmp/altv-js-module/commit/eefa41d05ac2381c2caec520f1c66da7f624c7b5 (I tested it)
