### ISSUE TITLE
Not full info about error

### ISSUE THREAD

**Issue by dominion56** [altmp/altv-js-module#157]
### Description of the problem

i have an error in my scripts, but i can't find what exacly happends. It doesn't show full info about error. I just have 
[16:24:22] [V8] Starting script client/index.js
[16:24:22][Error] [V8] Unhandled promise rejection at diserv:<bootstrapper>:13 (Error: 1 or 2 arguments expected)
[16:24:22][Error]   at [anonymous] (<bootstrapper>:13)

### Reproduction steps

i don't know because i can't find what happened

### Expected behaviour

info about error

### Operating system

win 10 64

### Version

10,5 release

### Scope

client

**Comment by LeonMrBonnie** [comment]
The info there is the info V8 provides, if there is no more info; I can't do anything to change that.

**Comment by xxshady** [comment]
@LeonMrBonnie i think he means this:
![изображение](https://user-images.githubusercontent.com/54737754/170783673-8a203b61-4be0-45f2-a6aa-0b62aaaf75fc.png)

clientside startup errors are not displayed correctly because of the js bootstrapper
