### ISSUE TITLE
rmlui event - sender not accessible

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-js-module#161]
### Description of the problem

Used example: click event, but basically belongs to all events

The sender in the rml event is always passed as number with value 0, so if multiple buttons have the same event (but with differnet e.g. id) there is no way to access the element id or the sender at all. According to [rmlui docs](https://mikke89.github.io/RmlUiDoc/pages/rml/events.html) the button should be passed (and is in the [c++ sdk](https://github.com/altmp/cpp-sdk/blob/master/events/CRmlEvent.h)).

### Reproduction steps

Start [sample resource](https://github.com/altmp/altv-issues/files/8870605/rmlui.zip)
Press "O" and click any of the buttons + see logs. Button is always passed as 0.

### Expected behaviour

Having access to the senders RmlElement object

### Additional context

Possible workaround:
As the js module gets the sender it can be passed as first argument of the event

### Operating system

Windows 11

### Version

release/10.10

### Scope

client

**Comment by vanlueckn** [comment]
Isn't this fixed with  #171?

**Comment by deluvas1911** [comment]
good point, I forgot about that issue xd
