### ISSUE TITLE
Lost context when using setTimeout inside `connectionQueueAdd` event

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-js-module#163]
### Description of the problem

Currently, when having the following `connectionQueueAdd` callback, the following error is thrown

![image](https://user-images.githubusercontent.com/67131061/173182999-8934da0c-e02c-462e-9a1e-cfc87dad1266.png)

### Reproduction steps

Use `alt.setTimeout` inside the `connectionQueueAdd` event like so:
```ts
alt.setTimeout(connectionInfo.accept, 10_000); 
```

### Expected behaviour

The above lines of Code should be working

### Additional context

When using an lambda callback inside `alt.setTimeout` it does work as it should:
```ts
alt.setTimeout(() => connectionInfo.accept(), 10_000); 
```

### Operating system

Windows 10

### Version

release/10.1

### Scope

server

**Comment by LeonMrBonnie** [comment]
As this is expected behaviour with how JS functions work, I will not try to add a hacky fix by binding the function.
Either you do that yourself manually, or just use a lambda like you suggested.

The crash was fixed in f3015eac995f0c7d221f36db40acf553c347a2f0 though.
