### ISSUE TITLE
setEntityAlpha after exiting Vehicle gets reseted

### ISSUE THREAD

**Issue by WolfsCoding** [altmp/altv-js-module#165]
### Description of the problem

After you set the alpha from a player with the native setEntityAlpha and the player went out of a vehicle the alpha gets reseted 

### Reproduction steps

set the players alpha player go in and out of a vehicle and the alpha gets reseted

### Expected behaviour

The player keeps the alpha

### Operating system

Windows 11

### Version

10.0-rc9

### Scope

client

**Comment by LeonMrBonnie** [comment]
Wrong repository to post this issue.
Also this issue is already opened https://github.com/altmp/altv-issues/issues/528
