### ISSUE TITLE
Resources import do not work when they are restarted

### ISSUE THREAD

**Issue by AmmoliteOff** [altmp/altv-js-module#166]
### Description of the problem

Restarting the main resource (not imported) throws an error

### Reproduction steps

1. Use resource import
2. Restart the resource
3. Get error

### Expected behaviour

Resource import works fine

### Additional context

Example:
`import * as chat from 'chat';` will produce an error after restarting the resource.
Possible solution:
`alt.Resource.getByName('chat')!.exports;`

### Operating system

Windows 10 Pro, 21H2

### Version

10.10 (release)

### Scope

shared

**Comment by LeonMrBonnie** [comment]
That is because of how the JS import system works, you can't change that import at runtime.
So unfortunately, this can't be fixed.
