### ISSUE TITLE
Port node.js / cef TextDecoder and TextEncoder to client

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-js-module#168]
### Description of the problem

There are some transport protocol clients (especially websocket clients) that use text encoding/decoding with TextEncoder/TextDecoder (like [phoenix websocket client library](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/serializer.js#L55))
Dunno about other cases, but it may be useful for someone who want to send/receive binary data and do something with it :thinking:

### Desired solution for the problem

Port it to client. There already browser/server (node.js) implementations. With such API it will be possible to port various websocket clients to altv client

### Alternatives you considered

Well, just use shim that may be outdated https://github.com/inexorabletash/text-encoding

### Version

release

### Scope

client

**Comment by LeonMrBonnie** [comment]
As the source code for JS module is fully open source here, anyone is welcome to try to implement this in the module.
But because of the very little demand there is for this feature (you are the first one asking for it), I won't spend my time on implementing it myself.
