### ISSUE TITLE
Client top level errors are displayed incorrectly

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#169]
### Description of the problem

![изображение](https://user-images.githubusercontent.com/54737754/176999766-3c929e9e-6e1e-4c0f-8c36-4b9bdfe073e0.png)

### Reproduction steps

Throw error on top level code.

### Expected behaviour

Error log should show the correct file, not the bootstrapper.

### Operating system

Windows 11

### Version

11.0-dev37

### Scope

client

**Comment by LeonMrBonnie** [comment]
This is due to how V8 handles reporting errors from dynamic import. Not possible to fix. Thanks V8 devs.
