### ISSUE TITLE
alt.Vector3 is not working inside worker thread

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-js-module#178]
### Description of the problem

Some methods do not seem to work on Vector3 within a worker thread. In my example it is the distanceTo method.

### Reproduction steps

1. create a clientside worker
2. Try to use Vector3 methods:

```
console.log('A ', currentVector instanceof alt.Vector3, distance);
console.log('B ', currentPlayerPosition instanceof alt.Vector3, distance);
```

```
[20:32:45] A  true NaN
[20:32:45] B  true NaN
```

### Expected behaviour

DistanceTo should return a number

### Operating system

Windows 11

### Version

alt:V 12.13

### Scope

client

**Comment by C0kkie** [comment]
I think we can close this, since workers are deprecated with alt:V 13.0
