### ISSUE TITLE
Blips should take Vector3 as an argument

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-js-module#196]
### Description of the problem

You can only pass x, y, z

### Desired solution for the problem

Be able to pass `alt.Vector3` to the constructor

### Scope

server

**Comment by xxshady** [comment]
Vector3 interface will be better

**Comment by ZackaryH8** [comment]
> Vector3 interface will be better

I looked at implementing it but not sure how to handle it because the argument length check of 1 is already used on pointblip for passing an entity.
