### ISSUE TITLE
Date object not passed correctly by emitClient

### ISSUE THREAD

**Issue by Iubotch** [altmp/altv-js-module#2]
Fetching a DATE data type value from a MySQL table and sending it to the client via emitClient does not work. The Date object is converted to a [Object object] and is empty. 

Client side:

![image](https://user-images.githubusercontent.com/62577366/84081621-9b350b00-a9de-11ea-8b12-71d503d8bc9f.png)

Outputs: [23:04:48] DATE CREATED: [object Object]

Server side:

![image](https://user-images.githubusercontent.com/62577366/84081907-244c4200-a9df-11ea-8eec-decf7f05986e.png)

Outputs:
2020-05-29T22:00:00.000Z

**Comment by 7Hazard** [comment]
test

**Comment by 7Hazard** [comment]
test

**Comment by micaww** [comment]
The devs can decide whether to handle dates specifically or not, but the reason this is happening is that `Date` is not a primitive.

If you want to pass it between contexts, you'll have to serialize it on one side and parse it on the receiving end:
```js
// server
const date = new Date();

alt.emitClient(player, 'sendDate', date.toJSON());

// client
alt.onServer('sendDate', dateJSON => {
    const date = new Date(dateJSON);

    // now you have a date object
});

**Comment by LeonMrBonnie** [comment]
As this is not an issue with the JS module but a suggestion for the alt:V Module SDK, refer to this issue https://github.com/altmp/altv-issues/issues/1118.
