### ISSUE TITLE
Add toFixed to vectors

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-js-module#203]
### Description of the problem

Sometimes I don't want a really precise vector and end up using toFixed on each value

### Desired solution for the problem

Provide a `.toFixed` method on Vector2 and Vector3 classes so x, y, z can be truncated

### Alternatives you considered

```ts
declare module 'alt-shared' {
    export interface Vector3 {
        toFixed(decimals: number): Vector3;
    }
}
```

```ts
import * as alt from 'alt-shared';

alt.Vector3.prototype.toFixed = function (decimals: number = 3): alt.Vector3 {
    return new alt.Vector3(this.x.toFixed(decimals), this.y.toFixed(decimals), this.z.toFixed(decimals));
};
```

### Scope

shared

**Comment by LeonMrBonnie** [comment]
If you have already written the code for it, why don't you just add it yourself and make a PR?

**Comment by ZackaryH8** [comment]
Just aa reminder for me to add it
