### ISSUE TITLE
weapon event cant work

### ISSUE THREAD

**Issue by PassWordE** [altmp/altv-js-module#215]
### Description of the problem

alt.on('playerWeaponChange', (oldWeapon, newWeapon) =>{
    console.log('playerWeaponChange');
});

alt.on('playerWeaponShoot', (weapon, totalAmmo, ammoInClip) =>{
    console.log(weapon, totalAmmo, ammoInClip);
});

when switch weapon or shoot, console have no output

### Reproduction steps

see Description

### Expected behaviour

see Description

### Operating system

Windows 11

### Version

release/12.10

### Scope

server, client

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
In *Version* section you wrote release, but these features are only available in dev branch, see upcoming release on the docs:
https://docs.altv.mp/articles/changelogs/upcoming.html

**Comment by xxshady** [comment]
In *Version* section you wrote release, but these features are only available in dev branch, see upcoming release on the docs:
https://docs.altv.mp/articles/changelogs/upcoming.html

also in the api docs it has "dev" only icon
https://docs.altv.mp/js/api/alt-client.IClientEvent.html#_altmp_altv_types_alt_client_IClientEvent_playerWeaponShoot
