### ISSUE TITLE
Move away from macros

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-js-module#218]
### Description of the problem

Instead of using macros, we should instead opt to use a generic function for alot of binding related code

### Desired solution for the problem

/

### Additional context

In the best case, we can use regex to convert this in the whole codebase once functions for it have been added

### Scope

shared

**Comment by YannBcf** [comment]
What is the motivation ?

**Comment by LeonMrBonnie** [comment]
> What is the motivation ?

My depression caused by working on this codebase

**Comment by LeonMrBonnie** [comment]
#230 Will take care of this instead
