### ISSUE TITLE
Adding V8's HeapSnapshot function to the client

### ISSUE THREAD

**Issue by PlumeDreams** [altmp/altv-js-module#221]
### Description of the problem

Adding client-side heap snapshots allows users to handle their memory leaks

### Desired solution for the problem

V8 has it own function to `writeHeapSnapshot` , just call it and add the client console command, then generate the file in the altv root directory.

### Additional context

 v8.writeHeapSnapshot(filename);

### Scope

client

**Comment by LeonMrBonnie** [comment]
Added in 3c1fd78a5e4ac048fa97dd3765b81d2d613d9d84
