### ISSUE TITLE
Missing Clothes ID's in clothes.bin? Invisible or Wrong Clothes Sync Error

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-js-module#222]
### Description of the problem

Female Component ID 11 drawable from 415 to 437
Male Component ID 11 drawable from 402 to 408

For details look down alle issue ID's There

Whats wrong?
If you set on server with .setclothes this components
The Player itself See the clothes
Other players arround See 80% Nothing Or a Wrong (Blue JAcked but its White Shirt)

Idk Why but for ID 415 server deteckts for Component 11 Draw 415 Texture 15 DLC Hash 1224880856
for the same draw but Texture 16 to 25 (the issue related) No DLC Hash
Draw 415 Texture 15 works Without issues Draw 415 Texture 16 to 25 have the issues

_____________
Offtopic Report on Check This on Dev Build:

On Curret Dev Release Draw 415 texture 15 Returns not DLC 1224880856 it returns DLC 0
Related to the different Response from Release to Develope  from DLC1224880856  to DLC 0 (on this specific example) i have a massive issue Display of clothes  with clothes set on a Release Scan build Database ( of GTA clothes scanned before with getdlcclothes)
A Female char On Release fit White Shirt and White Pants looks on Dev Release like a StormTrooper (all GTA default clothes)

Make sense that the char fits different clothe if dev gives other dlc informations Back then Release, i set the GTA Base Clothe that reported on Release as DLC information with setdlcclothes from Database that the Release Version Returned before.
Component 11 Draw 415 texture 15 Saved in Database as
DLC: 1224880856 Drawable: 0 Texture: 15 Palette: 15 and will set with this values from Release with setdlcclothes on dev (but there it now returns DLC: 0 Drawable: 415 Texture: 15 Palette: 15 so this gives a error of not found DLC Clothes DLC: 1224880856 Drawable: 0 Texture: 15 Palette: 15

idk but there are many suspect issues on my dev test like no "reconnect" on reconnect ("connectionComplete" events not triggert on reconnect , in older v13 it worked) so i am not true if my DevBuild is Broken on my client/server , longt time dev release not used, realy Suspect

Edit: make sense the issue related Dev and Release Build

results of server side setclothes
Release
Comp: 11 Draw: 415 Texture: 15
https://prnt.sc/CxOOX8ZHN2ON
Comp: 11 Draw: 415 Texture: 16
https://prnt.sc/ehrbDUaM1i-9
Develope
Comp: 11 Draw: 415 Texture: 15
https://prnt.sc/QYtLtVgzHDD3
Comp: 11 Draw: 415 Texture: 16
https://prnt.sc/nx3zLa0RPsNu

_____________

Exaktly not working

Female:
componentId;drawableId;textureId;paletteId
11;437;25;25
11;437;24;24
11;437;23;23
11;437;22;22
11;437;21;21
11;437;20;20
11;437;19;19
11;437;18;18
11;437;17;17
11;437;16;16
11;437;15;15
11;437;14;14
11;437;13;13
11;437;12;12
11;437;11;11
11;437;10;10
11;437;9;9
11;437;8;8
11;437;7;7
11;437;6;6
11;437;5;5
11;437;4;4
11;437;3;3
11;437;2;2
11;437;1;1
11;435;2;2
11;435;1;1
11;432;25;25
11;432;24;24
11;432;23;23
11;432;22;22
11;432;21;21
11;432;20;20
11;432;19;19
11;432;18;18
11;432;17;17
11;432;16;16
11;432;15;15
11;432;14;14
11;432;13;13
11;432;12;12
11;432;11;11
11;432;10;10
11;432;9;9
11;432;8;8
11;432;7;7
11;432;6;6
11;432;5;5
11;432;4;4
11;432;3;3
11;432;2;2
11;432;1;1
11;428;25;25
11;428;24;24
11;428;23;23
11;428;22;22
11;428;21;21
11;428;20;20
11;428;19;19
11;428;18;18
11;428;17;17
11;428;16;16
11;428;15;15
11;428;14;14
11;426;13;13
11;426;12;12
11;426;11;11
11;426;10;10
11;426;9;9
11;426;8;8
11;426;7;7
11;426;6;6
11;426;5;5
11;426;4;4
11;426;3;3
11;426;2;2
11;426;1;1
11;415;25;25
11;415;24;24
11;415;23;23
11;415;22;22
11;415;21;21
11;415;20;20
11;415;19;19
11;415;18;18
11;415;17;17
11;415;16;16

Male:
componentId;drawableId;textureId;paletteId
11;408;2;2
11;408;1;1
11;404;25;25
11;404;24;24
11;404;23;23
11;404;22;22
11;404;21;21
11;404;20;20
11;404;19;19
11;404;18;18
11;404;17;17
11;404;16;16
11;404;15;15
11;404;14;14
11;402;13;13
11;402;12;12
11;402;11;11
11;402;10;10
11;402;9;9
11;402;8;8
11;402;7;7
11;402;6;6
11;402;5;5
11;402;4;4
11;402;3;3
11;402;2;2
11;402;1;1

### Reproduction steps

You need 2 Players
Player 1 Set over Server player.setclothes one of the Above Related Issue ID's
Player 1 See the Clothes
Player 2 See Nothing (prev weared clothes removed)  or a Wrong Draw+Texture

### Expected behaviour

Same set of clothes for every player

### Operating system

Linux

### Version

release 12.21

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
if i See this now related of the debug testing in dev that the Release Version clothes.bin is filled with Bad/Wrong data?
And The missing Sync of the not Included data and filled with Wrong/Bad Data of the "synced"?

other i can't understand this visual results  of 2 different draw in release and the total different draw's of the same  415 texture 15 in Release and Develope 
results of server side setclothes
Release
Comp: 11 Draw: 415 Texture: 15
https://prnt.sc/CxOOX8ZHN2ON
Comp: 11 Draw: 415 Texture: 16
https://prnt.sc/ehrbDUaM1i-9
Develope
Comp: 11 Draw: 415 Texture: 15
https://prnt.sc/QYtLtVgzHDD3
Comp: 11 Draw: 415 Texture: 16
https://prnt.sc/nx3zLa0RPsNu

**Comment by LeonMrBonnie** [comment]
Not related to JS module, reopen this in the https://github.com/altmp/altv-issues repo
