### ISSUE TITLE
baseObjectCreate weird behavior

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#233]
### Description of the problem

![изображение](https://user-images.githubusercontent.com/54737754/205503877-cb0026b7-f1c7-4650-9f14-dae057cc1929.png)
![изображение](https://user-images.githubusercontent.com/54737754/205503884-54699c62-1c41-40e9-98f2-797b885b27c0.png)
and when i try to access `baseobj.id` property it crashes the server

### Reproduction steps

```js
import alt from "alt-server"
alt.on("baseObjectCreate", (baseobj) => {
  alt.log("baseObjectCreate", baseobj)

  alt.nextTick(() => {
    alt.log(baseobj === veh, baseobj.id, veh.id, baseobj)
  })
})
const veh = new alt.Vehicle("sultan2", alt.Vector3.zero, alt.Vector3.zero)
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

13.0-dev-63

### Scope

shared

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Event got removed for now

**Comment by xxshady** [comment]
xd https://github.com/altmp/altv-issues/issues/1098#issuecomment-917669248
