### ISSUE TITLE
Raw event sends long string as arraybuffer

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#247]
### Description of the problem

/

### Reproduction steps

```js
const BROKEN = 2 ** 20
const NORMAL_STRING = 2 ** 19

let str = ""
for (let i = 0; i < BROKEN; ++i) { // try replacing this with NORMAL_STRING and it will be sent as string
  str += "1"
}
alt.emitServerRaw('test', str)
```

```js
alt.onClient("test", (_player, base64) => {
  alt.log("base64", typeof base64, base64.length) // prints type: object
})
```

### Expected behaviour

String should be send as string

### Operating system

Windows 11

### Version

release 13.48 thanks to gta update

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
thats how the serializer works, it wont be fixed

**Comment by xxshady** [comment]
@LeonMrBonnie Cannot this be turned into an error at least if string is too long?

**Comment by xxshady** [comment]
@C0kkie
