### ISSUE TITLE
Confusing `alt:` import error

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#249]
### Description of the problem

If you import a resource that does not exist, you will get this confusing error:
![изображение](https://user-images.githubusercontent.com/54737754/226588568-7da3d971-dfad-4c73-b539-bf4994691276.png)

### Reproduction steps

```js
import awdawdawdjfds from "alt:addgjdfgkjdkfggdfg"
```

### Expected behaviour

Error should tell you that such resource does not exist

### Operating system

Windows 11

### Version

14.0-rc3

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Phill030** [comment]
imo that's pretty obvious 🤷‍♂️

**Comment by xipanca** [comment]
I have the same problem

**Comment by LeonMrBonnie** [comment]
Fixed
