### ISSUE TITLE
alt.Vehicle.streamedIn array is always empty

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-js-module#270]
### Description of the problem

`alt.Vehicle.streamedIn` is always empty - even when you're in the same dimension of the vehicle and you've also spawned the player using `player.spawn`. In release branch it works as intended. You also see the vehicle which you've created. In my testing, dimensions were both 0.

### Reproduction steps

- Spawn the player using `player.spawn` as usual
- Spawn a vehicle in the same dimension as you
- Log `alt.Vehicle.streamedIn.length` on Client-side

### Expected behaviour

`alt.Vehicle.streamedIn` should contain all currently streamedIn vehicles.

### Additional context

I'm not sure but this issue might affect other `.streamedIn` properties aswell? I'm going to update this once i've done some more debugging

### Operating system

Windows 11

### Version

15.0-dev179

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Maybe it's related ti C# Module then?

What i simply do is:
 1. Conenct to the server (set model and spawn on connect)
 2. Spawn vehicle
 3. baseObjectCreate / baseObjectRemove seem to be called on dev now, however, streamedIn is still empty.
 
 Also tested on a blank C# resource which only receives an event from the client to spawn the vehicle (consoleCommand) and the connect handler which is the following:

![rider64_3pdBHVqVSP](https://github.com/altmp/altv-js-module/assets/67131061/401e3e94-6270-40e9-a4b9-37f9db0eef2c)

The vehicle creation is simply just the following:
![rider64_c8PsDk9zkf](https://github.com/altmp/altv-js-module/assets/67131061/5d1c6a25-511f-4a2e-be04-4febfcd80c24)

The client-side only contains the snippet provided above with another command sending an event to the server.

**Comment by xxshady** [comment]
Now `alt.Vehicle.streamedIn` getter crashes client xd
