### ISSUE TITLE
`alt.LocalObject.all` contains nulls after resource restart

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#281]
### Description of the problem

`alt.LocalObject.all` getter returns array with nulls (non-destroyed objects before resource was stopped) after resource restart

![изображение](https://github.com/altmp/altv-js-module/assets/54737754/6fe3c8e4-bb0c-4ba6-b1fb-1c0380380ebc)
> old image, alt.LocalObject was named alt.Object before

### Reproduction steps

1. Execute this code
```js
new alt.LocalObject(
  'stt_prop_stunt_soccer_ball',
  new alt.Vector3(0, 7, 72),
  alt.Vector3.zero,
)
alt.log('alt.LocalObject.all:', alt.LocalObject.all)
```
2. Restart resource

### Expected behaviour

Objects should be removed from `alt.LocalObject.all` array after resource restart

### Operating system

Windows 11

### Version

15.0-dev291

### Scope

client

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
can't reproduce on latest `dev` using the following code:
```js
new alt.Object('stt_prop_stunt_soccer_ball', new alt.Vector3(0, 7, 72), alt.Vector3.zero)
alt.log('alt.Object.all:', alt.Object.all.map((o) => o instanceof alt.Object))
```

<img src="https://i.imgur.com/S0Goziy.png" />

**Comment by xxshady** [comment]
@xLuxy it was clientside issue

**Comment by xxshady** [comment]
before release of v15 alt.LocalObject was named alt Object

**Comment by xxshady** [comment]
@xLuxy is it fixed?

**Comment by xLuxy** [comment]
Read my message above.

xshady ***@***.***> schrieb am Di., 30. Juli 2024, 16:49:

**Comment by xxshady** [comment]
@xLuxy did you read my message that followed yours? xd

**Comment by xxshady** [comment]
> before release of v15 alt.LocalObject was named alt.Object

on your screen its alt.Object, this issue is about alt.LocalObject
