### ISSUE TITLE
baseobject is not of type alt::IVirtualEntity

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module#299]
### Description of the problem

When streaming in/out virtual entities, this error commonly comes out:
Client:
![image](https://github.com/altmp/altv-js-module/assets/9081457/b1cbb2f5-5e7c-4adb-b424-01332605ff45)
![image](https://github.com/altmp/altv-issues/assets/9081457/c491d498-8adb-44c2-9319-2274297c50b9)

Server:
![image](https://github.com/altmp/altv-issues/assets/9081457/1703c37c-313d-4863-b4ea-7a83c1fe57c4)

### Reproduction steps

In my case, I've created ~30k of virtual entities around the map with 30 streamed-in limit, zoomed around area back and forth and this error consistently comes up.

### Expected behaviour

The code should not throw an error.

### Additional context
https://discord.com/channels/371265202378899476/576771706119520287/1147987791460958348

### Operating system

Win11

### Version

15.0-dev595

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Yiin** [comment]
Some additional context: The entity in question is coming from Map keys.
```ts
const map = new Map<alt.VirtualEntity, Foo>();

function foo() {
  for (const entity of Object.keys(map)) {
    const type = getAnchorType(entity);
    ...
  }
}
```

**Comment by xLuxy** [comment]
Can't reproduce that using the following snippet:
```js
const map = new Map();

alt.onServer('gotMe', () => {
  const entity = alt.VirtualEntity.all[0];

  for (let i = 0; i < 20; ++i) {
    map.set(i, entity)
  }

  for (const entity of map.values()) {
    const val = entity.getStreamSyncedMeta('test');
    alt.log(val, entity.id);
  }

  /*for (const [, entity] of map.entries()) {
    const val = entity.getStreamSyncedMeta('test');
    alt.log(val, entity.id);
  }*/
});
```

Please provide working code to reproduce this.

**Comment by Yiin** [comment]
xLuxy is a goat

(tracking entities using `worldObjectStreamIn` & `worldObjectStreamOut` events is the way).
