### ISSUE TITLE
RPC freezed after second call

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-js-module#305]
### Description of the problem

If you're using `emitRpc` every 1 second, server will freeze.

### Reproduction steps

```js
// Client side
setInterval(async () => {
    const data = await alt.emitRpc('giveMeData');
}, 1000);
```
```js
// Server side
alt.onRpc('giveMeData', async () => {
    await alt.Utils.wait(500);
    return 123;
});
```

### Expected behaviour

Should not freeze.

### Additional context

Nothing.

### Operating system

Windows 10

### Version

dev/15.0-dev711

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Fixed in server (`dev/15.0-dev717`) - on client it will be fixed once module is updated in core
