### ISSUE TITLE
Vehicle creation doesn't work with player.pos & player.rot

### ISSUE THREAD

**Issue by litolax** [altmp/altv-js-module#306]
### Description of the problem

If I try to create vehicle with constructor (player.pos, player.rot):
I have 
![image](https://github.com/altmp/altv-js-module/assets/60060712/b6bc131c-a07c-4846-85c5-c55b6cf3c5e7)
Constructor with player.pos.x, player.pos.y, etc, works fine
![image](https://github.com/altmp/altv-js-module/assets/60060712/5a7fbe2a-d060-4c1c-bf98-00d3f191bd7c)

### Reproduction steps

```js
globalThis.veh = new alt.Vehicle("t20", player.pos, player.rot, 200);
```

### Expected behaviour

Creation should work properly

### Operating system

Windows 10

### Version

dev/15.0-dev722

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module/commit/1de7c1d9ac4fcb544b504ed64fa5efbeedeed824
