### ISSUE TITLE
Missing wheelVariation at alt.Vehicle

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-js-module#315]
### Description of the problem

The following value "wheelVariation" is missing on the server side

### Desired solution for the problem

.

### Version

16.0.0-dev.327

### Scope

server

**Comment by xLuxy** [comment]
The SDK currently doesn't provide a setter for it - so it's not related to the JS module unless the method name is cryptic in cpp-sdk and can't be found.

**Comment by BluePeer** [comment]
Question, this is other then the default Variation?
if not then this is default set by vehicle.setWheels(Type,variation)
or it this another ?
this is the value you read out in c# on wheelVariation set by setwheels
RearWheel is a get/set for the read variation (of type from setwheels
