### ISSUE TITLE
everytick stop after a while

### ISSUE THREAD

**Issue by dictateurfou** [altmp/altv-js-module#34]
**Describe the bug**
everytick stop after a while
(only tested on server)

**To Reproduce**
make everytick and wait

My everytick

```JS
let lastTime = Date.now()
everyTick(() => {
    const newTime = Date.now()
    if (newTime - lastTime >= 3500) {
        moduleAntiSpam = {}
        lastTime = Date.now()
    }
})
```
OS: Debian 11
alt:V server version: 3.0-dev14
Other installed modules: csharp-module
JS module version: 3.0-dev14

**Comment by LeonMrBonnie** [comment]
Duplicate #32
