### ISSUE TITLE
DynamicImport doesn't work before connectionComplete

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-js-module#78]
### Description of the problem

await import( './file' )

or import( './file' ).then().catch().finally()

only works after the connectionComplete event got fired.

### Reproduction steps

```JS
import * as alt from 'alt-client';

async function loadBeforeConnectionComplete() {
    alt.log( "You can see me" );
    await import( './lib/utils' );
    alt.log( "You will never see me" );
}

async function loadAfterConnectionComplete() {
    alt.log( "Hey, are you ok?" );
    await import( './lib/utils' ); // if set to a const you can use any export
    alt.log( "I'm fine!" );
}

loadBeforeConnectionComplete();

alt.on("connectionComplete", () => {
    loadAfterConnectionComplete();
});
```

File 2 can be just empty. The import/exports are working, as soon the event got triggered.

### Expected behaviour

Make it work on startup.

### Operating system

Windows

### Version

Current/release

### Scope

client

**Comment by LeonMrBonnie** [comment]
There was no response anymore so I will close the issue.
If you can provide reliable reproduction steps, the issue can be reopened.
