### ISSUE TITLE
Serverside alt.Blip.routeColor throws invalid baseobject error

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#85]
### Description of the problem

Serverside static getter alt.Blip.routeColor throws baseobject error

### Reproduction steps

```js
try{ alt.Blip.routeColor } catch(e) { console.error(e) }
```

### Expected behaviour

No error.

### Operating system

Windows 10

### Version

dev/7.0-dev13

### Scope

server

**Comment by FabianTerhorst** [comment]
I checked and routeColor is not static.
