### ISSUE TITLE
Allow base64 string as dynamic import path / worker path

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-js-module#86]
### Description of the problem

Add the ability to use a base64 string in file paths for workers / dynamic imports, that loads that base64 string as code, instead of a file.
Should also be available for `alt.evalModule`

### Desired solution for the problem

```js
let result = alt.evalModule("data:text/javascript;base64,J2EnIDwgJ2In"); // "'a' < 'b'" as base64
```

Check if string starts with `data:text/javascript;base64,`, then the text after that is the actual base64 string.

### Additional context

This is particularly useful for the usage with bundlers.

### Scope

client

**Comment by YannBCF** [comment]
Type assertions
