### ISSUE TITLE
(RELEASE) alt.Player:getMeta returns empty array as empty object

### ISSUE THREAD

**Issue by Quantum2707** [altmp/altv-js-module#91]
### Description of the problem

Hey,

so when I set the player meta serverside using `alt.Player:setMeta` to be an empty array `[]` and get it using `alt.Player:getMeta` it returns an empty object `{}` instead of an empty array.

Cheers.

### Reproduction steps

For Testing:

1. Set player meta on join -> `player.setMeta('myMeta', []);`
2. Read the meta next step and print it somewhere -> `player.getMeta('myMeta');`
3. See it returns `{}` instead of `[]`

### Expected behaviour

It should return an empty array when an empty array was set on this key.

### Operating system

Windows 10

### Version

release

### Scope

server

**Comment by LeonMrBonnie** [comment]
Can't reproduce on newest dev.
```js
alt.on("playerConnect", (player) => {
    player.setMeta("test", []);
    let result = player.getMeta("test");
    alt.log(typeof result);
    alt.log(Array.isArray(result));
    alt.log(result);
});
```
```
[17:08:59] object
[17:08:59] true
[17:08:59]
```
